{
 "title": "Arena",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "arena",
    "query": {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> distinct(column: \"arena\")"
    }
   },
   {
    "name": "character",
    "query": {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"character\")\r\n  |> distinct(column: \"character\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current turn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Turn" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"turn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total agent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total alive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alive\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total death",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"death\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total golds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Golds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"golds\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"arena\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Agent life",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"character\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"life\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Golds",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"golds\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total alives",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"arena\"] == \"${arena}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alive\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}